apiVersion: v1
kind: Service
metadata:
  name: innovation-backend-svc
  namespace: innovation-enterprise
spec:
  selector:
    app: innovation-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
