services:
  - type: web
    name: innovation-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd innovation && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
